apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-service-deploy
  labels:
    app: metadata-service
spec:
  replicas: 4
  selector:
    matchLabels:
      app: metadata-service
  template:
    metadata:
      labels:
        app: metadata-service
    spec:
      containers:
        - name: metadata-service-container
          image: metadata-service:1.0
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 3
