apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongo-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts: 
            - mountPath: /data/db
              name: test-volume
      volumes:
      - name: test-volume
        hostPath:
          path: /home
          type: Directory